name: Countdown
main: Countdown\Main
version: 1.0.0
api: 2.0.0
commands:
 countdown:
  description: "Countdown Commands & Info!"
  usage: "/countdown"
  permission: "countdown.command"
  aliases: [cd, countd, downc]
 cdstart:
  description: "Start a countdown!"
  usage: "/cdstart"
  permission: "countdown.start"
  aliases: [countdownstart, countdstart, cds]
